name: treatlab_new
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.2.0
  flutter_multiselect: ^1.0.0
  http: ^1.2.1
  intl: ^0.19.0
  multi_select_flutter: ^4.1.3
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
    - assets/icons/
  uses-material-design: true
